version: '2'
services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: blog_api-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: blog_api
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    environment:
      - XDEBUG_ENABLED=true
    command: /var/www/app/start.sh
    links:
      - mysql